common:
  docker_put: &docker_put
    params:
      build: source-code
      tag_as_latest: false
    get_params:
      skip_download: true

jobs:
- name: build
  serial: true
  plan:
  -
    on_success:
      put: slack-notify
      params:
        text: mqtt-http-gateway released 🥳
    on_failure:
      put: slack-alert
      params:
        text: mqtt-http-gateway pipeline failed 😭
    do:
    - get: source-code
      trigger: true
    - in_parallel:
      - put: amd64
        <<: *docker_put
      - put: armv7
        <<: *docker_put
    - put: image
      params:
        tag_file: source-code/.git/short_ref
        manifests:
        - arch: amd64
          os: linux
          digest_file: amd64/digest
        - arch: arm
          variant: v7
          os: linux
          digest_file: armv7/digest

resources:
- name: source-code
  type: git
  source:
    uri: git@github.com:timotto/mqtt-http-gateway.git
    private_key: ((github.private_key))
    branch: master
    ignore_paths:
    - pipeline.yml
    - README.md

- name: amd64
  type: docker-image
  source:
    repository: timotto/mqtt-http-gateway
    tag: amd64
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: armv7
  type: remote-docker-image
  source:
    repository: timotto/mqtt-http-gateway
    tag: armv7
    username: ((dockerhub.username))
    password: ((dockerhub.password))
    dockerd: ((dockerd))

- name: image
  type: docker-manifest
  source:
    repository: timotto/mqtt-http-gateway
    username: ((dockerhub.username))
    password: ((dockerhub.password))

- name: slack-notify
  type: slack-notification
  source:
    url: ((slack.low_prio_webhook_url))

- name: slack-alert
  type: slack-notification
  source:
    url: ((slack.webhook_url))

resource_types:
- name: remote-docker-image
  type: registry-image
  privileged: true
  source:
    repository: timotto/docker-image-resource
    tag: modernize

- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

- name: docker-manifest
  type: registry-image
  source:
    repository: mbialon/concourse-docker-manifest-resource
