apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "mqtt-http-gateway.fullname" . }}
  labels:
    app: {{ template "mqtt-http-gateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "mqtt-http-gateway.name" . }}
        release: {{ .Release.Name }}
      annotations:
{{- if $.Values.podAnnotations }}
{{ toYaml $.Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: DBURL
              value: {{ .Values.dburl | quote}}
            - name: DEBUG
              value: {{ .Values.debug | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
